server:
  port: 3001


spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379


## Session 过期时间，默认单位为 s
#  server.servlet.session.timeout=600
#  Session 存储到 Redis 键的前缀
#  spring.session.redis.namespace=test:spring:session